/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OurChurchRouteImport } from './routes/our-church'
import { Route as MediaEventsRouteImport } from './routes/media-events'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OurChurchRoute = OurChurchRouteImport.update({
  id: '/our-church',
  path: '/our-church',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaEventsRoute = MediaEventsRouteImport.update({
  id: '/media-events',
  path: '/media-events',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/get-involved': typeof GetInvolvedRoute
  '/media-events': typeof MediaEventsRoute
  '/our-church': typeof OurChurchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/get-involved': typeof GetInvolvedRoute
  '/media-events': typeof MediaEventsRoute
  '/our-church': typeof OurChurchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/get-involved': typeof GetInvolvedRoute
  '/media-events': typeof MediaEventsRoute
  '/our-church': typeof OurChurchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/get-involved'
    | '/media-events'
    | '/our-church'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/get-involved'
    | '/media-events'
    | '/our-church'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/get-involved'
    | '/media-events'
    | '/our-church'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  MediaEventsRoute: typeof MediaEventsRoute
  OurChurchRoute: typeof OurChurchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-church': {
      id: '/our-church'
      path: '/our-church'
      fullPath: '/our-church'
      preLoaderRoute: typeof OurChurchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-events': {
      id: '/media-events'
      path: '/media-events'
      fullPath: '/media-events'
      preLoaderRoute: typeof MediaEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  MediaEventsRoute: MediaEventsRoute,
  OurChurchRoute: OurChurchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
